name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Hard Reset Gradle Cache
      run: rm -rf ~/.gradle/caches/

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.0.2'
        cache-disabled: true   # <-- Запрещаем GitHub использовать твой битый кэш

    - name: Build APK
      run: gradle assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: IK-Antivirus
        path: app/build/outputs/apk/debug/app-debug.apk
