name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 1. Скачиваем твой код
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Ставим Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'

    # 3. Качаем Gradle 8.0.2 напрямую (без обёрток и без 9.3.0)
    - name: Download Gradle 8.0.2
      run: wget https://services.gradle.org/distributions/gradle-8.0.2-bin.zip && unzip -q gradle-8.0.2-bin.zip

    # 4. Собираем APK через скачанную папку gradle-8.0.2
    - name: Build APK
      run: ./gradle-8.0.2/bin/gradle assembleDebug

    # 5. Выдаём тебе готовый файл
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: IK-Antivirus
        path: app/build/outputs/apk/debug/app-debug.apk
